name: CI

on:
  push:
  pull_request:

jobs:
  example-build:
    name: Build example web widget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install SDK deps
        run: npm ci
      - name: Install example deps
        working-directory: examples/web-widget
        run: npm ci
      - name: Build example
        working-directory: examples/web-widget
        run: npm run build


